#!/bin/sh

check_output() {
    cmp .output.$1 .expected_output.$1 2>/dev/null >/dev/null
    if [ $? -eq 0 ]
    then
        echo "PASSED"
        #rm $1 $2
    else
        echo "FAILED"
        echo "Output from datalink binary is in file: .output.$1"
        echo "Expected output is in file: .expected_output.$1"
        echo "Debug output from datalink binary is in file: .debug_output.$1"
    fi
    echo
}

echo "###########################################################################"
echo "NOTE: Guidelines for using this script:"
echo "      - Tests check output written to stdout only."
echo "        If you have debug output in stdout, it may cause test failures."
echo "      - This is not a comprehensive set of test cases."
echo "        It is intended to help you do basic checks on your project."
echo "      - If your program fails any test, it will print the output files"
echo "        generated by your program and the output expected for the test case."
echo "      - The script should take about 20 seconds to complete."
echo "###########################################################################"
echo
echo
echo "Rebuilding datalink..."
make clean; make -j4 datalink
echo "Done rebuilding datalink"
echo





## Test Case 2
# echo -n "Test case 2: Sending 10 packets and expecting receiver to print them out in order: "
# (sleep 0.5; for i in `seq 0 255`; do echo "msg 0 0 Packet: $i"; sleep 0.1; done; sleep 1; echo "exit") | ./datalink -d 0.5 -c 0.5 -r 1 -s 1 > .output.1

echo -n "Test case 2: Sending 10 packets and expecting receiver to print them out in order: "
(sleep 0.5; for i in `seq 0 255`; do echo "msg $i $i There are moments in life when you miss someone so much that you just want to pick them from your dreams and hug them for real! Dream what you want to dream;go where you want to go;be what you want to be,because you have only one life and one chance to do all the things you want to do."; sleep 0.1; done; sleep 1; echo "exit") | ./datalink -d 0.5 -c 0.5 -r 256 -s 256 > .output.1




